###
POST http://localhost:3000/api/usuarios HTTP/1.1
Content-Type: application/json

{
    "nombre":"Miguel",
    "usuario": "mike",
    "password": "123456",
    "rol":"administrador"
}

###
GET http://localhost:3000/api/usuarios 

###
GET http://localhost:3000/api/enfermedades


###
GET http://localhost:3000/api/usuarios/642bb040bdc919c2df5e9236


###
PUT  http://localhost:3000/api/usuarios/642bb040bdc919c2df5e9236 HTTP/1.1
Content-Type: application/json

{
    "nombre":"Miguel",
    "usuario": "mike",
    "password": "1234566666",
    "rol":"administrador"


}

###
DELETE  http://localhost:3000/api/usuarios/642bb040bdc919c2df5e9236
